name: reverse-shell

on:
  workflow_dispatch:
#    branches: [ "main" ]
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
#    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install tools
      run: |
        brew update
        brew install netcat bash
#        brew install automake coreutils diffutils findutils gawk git-extras gnu-getopt gnu-sed grep make
    - name: configure
      run: ./configure
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
