name: reverse-shell

on:
  workflow_dispatch:
#    branches: [ "main" ]
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:

#    runs-on: macos-14
    runs-on: macos-latest
#    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install tools
      run: |
        brew update
        brew install bash netcat
        brew install gnu-sed gnu-which less quilt screen
        brew install automake coreutils diffutils findutils gawk gengetopt git-extras gnu-getopt gnu-sed gpatch grep make
        ./bin/tools-link
        ./bin/system-config
    - name: configure
      run: ./configure
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
